# Script for testing all mix-ins
before_script:
  - export GENTOO_MIRRORS="https://fastpull-us.funtoo.org http://distfiles.gentoo.org"
  - epro mix-in multilib

stages:
  - test

runtests:
  stage: test
  tags:
    - lxd
  script:
    - python3 ./runtests
